export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const LEVEL_REPOSITORY = Symbol('LEVEL_REPOSITORY');
export const PROGRESS_REPOSITORY = Symbol('PROGRESS_REPOSITORY');
export const LEADERBOARD_REPOSITORY = Symbol('LEADERBOARD_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
